apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: prometheus-k8s
  namespace: kubesphere-monitoring-system
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  clusterIP: None
  selector:
    app: prometheus
    prometheus: k8s
