apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: s2i-operator
  name: s2i-operator
  namespace: kubesphere-monitoring-system
spec:
  endpoints:
  - honorLabels: true
    interval: 1m
    metricRelabelings:
    - action: keep
      regex: s2i_s2ibuilder_created
      sourceLabels:
      - __name__
    port: http
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kubesphere-devops-system
  selector:
    matchLabels:
      app: s2i-metrics
      control-plane: s2i-controller-manager
