apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s-system
  name: k8s-system
  namespace: kubesphere-monitoring-system
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: kubesphere-monitoring-system
      port: web
  baseImage: dockerhub.qingcloud.com/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  query:
    maxConcurrency: 200
  replicas: 1
  resources:
    requests:
      memory: 400Mi
  retention: 7d
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  scrapeInterval: 1m
  secrets:
  - kube-etcd-client-certs
  securityContext:
    fsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: In
      values:
      - etcd
      - coredns
      - apiserver
      - prometheus
      - kube-scheduler
      - kube-controller-manager
      - kube-state-metrics
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 20Gi
  version: v2.5.0
