apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: alertmanager
  name: alertmanager
  namespace: kubesphere-monitoring-system
spec:
  endpoints:
  - interval: 1m
    port: web
  selector:
    matchLabels:
      alertmanager: main
